-- Esquema inicial de Adopet para PostgreSQL 18

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    correo VARCHAR(160) NOT NULL UNIQUE,
    telefono VARCHAR(30),
    direccion VARCHAR(250),
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_usuarios_rol
        CHECK (rol IN ('ADOPTANTE', 'ADMINISTRADOR'))
);

CREATE TABLE mascotas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    especie VARCHAR(50) NOT NULL,
    raza VARCHAR(80),
    sexo VARCHAR(20) NOT NULL,
    edad INTEGER NOT NULL,
    tamano VARCHAR(30),
    descripcion VARCHAR(1000),
    estado_salud VARCHAR(250) NOT NULL,
    imagen_url VARCHAR(500),
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT ck_mascotas_edad CHECK (edad >= 0),
    CONSTRAINT ck_mascotas_estado
        CHECK (estado IN ('DISPONIBLE', 'NO_DISPONIBLE', 'ADOPTADA'))
);

CREATE TABLE solicitudes_adopcion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    estado VARCHAR(20) NOT NULL,
    observaciones VARCHAR(1000),
    fecha_actualizacion TIMESTAMP,
    adoptante_id BIGINT NOT NULL,
    mascota_id BIGINT NOT NULL,
    CONSTRAINT ck_solicitudes_estado
        CHECK (estado IN ('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA', 'FINALIZADA')),
    CONSTRAINT fk_solicitudes_adoptante
        FOREIGN KEY (adoptante_id) REFERENCES usuarios (id) ON DELETE RESTRICT,
    CONSTRAINT fk_solicitudes_mascota
        FOREIGN KEY (mascota_id) REFERENCES mascotas (id) ON DELETE RESTRICT
);

CREATE TABLE seguimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    estado VARCHAR(50),
    observaciones VARCHAR(1000),
    solicitud_id BIGINT NOT NULL,
    CONSTRAINT fk_seguimientos_solicitud
        FOREIGN KEY (solicitud_id) REFERENCES solicitudes_adopcion (id) ON DELETE RESTRICT
);

CREATE INDEX idx_usuarios_correo ON usuarios (correo);
CREATE INDEX idx_mascotas_estado ON mascotas (estado);
CREATE INDEX idx_solicitudes_adoptante_id ON solicitudes_adopcion (adoptante_id);
CREATE INDEX idx_solicitudes_mascota_id ON solicitudes_adopcion (mascota_id);
