import { useEffect, useState } from 'react'
import { ClipboardList } from 'lucide-react'
import StatusPill from '../components/StatusPill'
import { requestsApi } from '../services/api'

export default function HistoryPage() {
  const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { requestsApi.history().then(({ data }) => setHistory(data)).catch(err => setError(err.response?.data?.mensaje || 'No pudimos cargar tu historial.')).finally(() => setLoading(false)) }, [])
  return <div><header><p className="eyebrow">Tu proceso</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Mis solicitudes.</h1><p className="mt-3 text-[#81786F]">Sigue cada paso de las historias que elegiste acompañar.</p></header>{error && <div className="mt-8 rounded-2xl bg-coral-50 p-5 text-sm font-semibold text-coral-700">{error}</div>}{loading ? <div className="surface mt-10 h-56 animate-pulse bg-[#F1ECE5]" /> : history.length ? <div className="surface mt-10 overflow-hidden"><div className="hidden grid-cols-[1fr_1fr_1fr_1.4fr] gap-4 border-b border-[#EEE7DD] bg-cream px-6 py-4 text-[11px] font-bold uppercase tracking-wider text-[#9A9187] sm:grid"><span>Solicitud</span><span>Fecha</span><span>Estado</span><span>Observaciones</span></div><div className="divide-y divide-[#F1ECE5]">{history.map(item => <div key={item.id} className="grid gap-3 px-6 py-5 sm:grid-cols-[1fr_1fr_1fr_1.4fr] sm:items-center sm:gap-4"><div><p className="font-bold text-ink">Solicitud #{item.id}</p><p className="mt-1 text-xs text-[#9A9187]">Mascota #{item.mascotaId}</p></div><p className="text-sm text-[#746C63]">{item.fecha}</p><div><StatusPill status={item.estado} /></div><p className="text-sm leading-5 text-[#81786F]">{item.observaciones || 'Sin observaciones adicionales.'}</p></div>)}</div></div> : <div className="surface mt-10 flex flex-col items-center px-6 py-20 text-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-sage-100 text-sage-700"><ClipboardList size={26} /></div><h2 className="mt-5 font-display text-2xl font-bold">Tu historial está esperando</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#81786F]">Cuando envíes una solicitud, podrás seguirla desde aquí.</p></div>}</div>
}
