import { useState } from 'react'
import { ArrowRight, Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import logo from '../../images/Logo_Adopet.png'

export default function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [form, setForm] = useState({ correo: '', contrasena: '' }); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { const account = await login(form); const destination = location.state?.from?.pathname || (account.rol === 'ADMINISTRADOR' ? '/admin' : '/catalogo'); navigate(destination, { replace: true }) } catch (err) { setError(err.response?.data?.mensaje || 'No pudimos validar tus datos. Revisa tu correo y contraseña.') } finally { setBusy(false) } }
  return <div className="grid min-h-screen lg:grid-cols-[0.9fr_1.1fr]">
    <section className="relative hidden overflow-hidden bg-coral-500 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-24 top-24 h-80 w-80 rounded-full border-[36px] border-white/10" /><div className="absolute -bottom-32 -left-20 h-96 w-96 rounded-full border-[50px] border-sage-300/30" /><div className="relative flex items-center gap-0"><img src={logo} alt="Adopet" className="relative -top-2 -mr-5 h-32 w-32 object-contain brightness-0 invert" /><span className="relative top-1 font-display text-4xl font-bold leading-none">adopet<span className="text-sunshine">.</span></span></div><div className="relative max-w-md"><p className="mb-5 text-sm font-bold uppercase tracking-[0.2em] text-white/65">Cada encuentro importa</p><h1 className="font-display text-6xl font-bold leading-[0.96]">Hogares que se encuentran.</h1><p className="mt-7 max-w-sm text-lg leading-8 text-white/80">Una forma más humana de descubrir a tu próxima compañía.</p></div><p className="relative text-sm text-white/60">Adopet · adopciones con cuidado</p></section>
    <section className="flex items-center justify-center bg-cream px-6 py-12"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-2 font-display text-2xl font-bold">adopet<span className="text-coral-500">.</span></div></div><div className="mb-9"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-sage-50 px-3 py-1.5 text-xs font-bold text-sage-700"><ShieldCheck size={14} /> Acceso seguro</div><h2 className="font-display text-4xl font-bold text-ink">Qué bueno verte.</h2><p className="mt-3 text-[#81786F]">Entra a tu espacio de Adopet y sigue una historia.</p></div><form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-ink">Correo electrónico</span><input className="field" type="email" required placeholder="tu@correo.com" value={form.correo} onChange={e => setForm({ ...form, correo: e.target.value })} /></label><label className="block"><span className="mb-2 block text-sm font-bold text-ink">Contraseña</span><div className="relative"><input className="field pr-12" type={show ? 'text' : 'password'} required placeholder="••••••••" value={form.contrasena} onChange={e => setForm({ ...form, contrasena: e.target.value })} /><button type="button" onClick={() => setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-[#968D83]" title="Mostrar contraseña">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p className="rounded-xl bg-coral-50 px-4 py-3 text-sm font-semibold text-coral-700">{error}</p>}<button className="primary-button w-full py-3.5" disabled={busy}>{busy ? 'Entrando...' : <>Entrar a Adopet <ArrowRight size={17} /></>}</button></form><p className="mt-7 text-center text-sm text-[#81786F]">¿Aún no tienes cuenta? <Link to="/registro" className="font-bold text-coral-600 hover:text-coral-700">Crea tu espacio</Link></p></div></section>
  </div>
}
