import { useState } from 'react'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import logo from '../../images/Logo_Adopet.png'

export default function RegisterPage() {
  const { register } = useAuth(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const [form, setForm] = useState({ nombre: '', documento: '', correo: '', telefono: '', direccion: '', contrasena: '' })
  function change(e) { setForm({ ...form, [e.target.name]: e.target.value }) }
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { await register(form); navigate('/login', { state: { registered: true } }) } catch (err) { setError(err.response?.data?.mensaje || 'No pudimos crear tu cuenta. Revisa los datos.') } finally { setBusy(false) } }
  return <div className="min-h-screen bg-cream px-5 py-6 sm:px-10"><div className="mx-auto max-w-5xl"><Link to="/login" className="inline-flex items-center gap-2 text-sm font-bold text-[#776F66] hover:text-coral-600"><ArrowLeft size={17} /> Volver al acceso</Link><div className="mt-10 grid overflow-hidden rounded-2xl border border-[#EEE7DD] bg-white shadow-soft lg:grid-cols-[0.75fr_1.25fr]"><section className="relative overflow-hidden bg-sage-700 p-9 text-white sm:p-12"><img src={logo} alt="Adopet" className="mb-16 h-12 w-12 object-contain" /><p className="eyebrow text-sage-300">Bienvenido a la manada</p><h1 className="mt-4 font-display text-5xl font-bold leading-tight">Tu historia también puede cambiar una vida.</h1><p className="mt-6 leading-7 text-white/75">Crea tu cuenta para conocer mascotas, enviar solicitudes y acompañar cada paso.</p></section><section className="p-7 sm:p-12"><h2 className="font-display text-3xl font-bold text-ink">Crear cuenta</h2><p className="mt-2 text-sm text-[#81786F]">Solo necesitas unos datos para empezar.</p><form onSubmit={submit} className="mt-8 grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Nombre completo</span><input className="field" name="nombre" required value={form.nombre} onChange={change} placeholder="Ana Torres" /></label><label><span className="mb-2 block text-sm font-bold">Documento</span><input className="field" name="documento" required value={form.documento} onChange={change} placeholder="123456789" /></label><label><span className="mb-2 block text-sm font-bold">Correo</span><input className="field" type="email" name="correo" required value={form.correo} onChange={change} placeholder="ana@correo.com" /></label><label><span className="mb-2 block text-sm font-bold">Teléfono</span><input className="field" name="telefono" value={form.telefono} onChange={change} placeholder="300 000 0000" /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Dirección</span><input className="field" name="direccion" value={form.direccion} onChange={change} placeholder="Calle 10 # 20-30" /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Contraseña</span><input className="field" type="password" name="contrasena" minLength="8" required value={form.contrasena} onChange={change} placeholder="Mínimo 8 caracteres" /></label>{error && <p className="sm:col-span-2 rounded-xl bg-coral-50 px-4 py-3 text-sm font-semibold text-coral-700">{error}</p>}<button className="primary-button sm:col-span-2" disabled={busy}>{busy ? 'Creando cuenta...' : <>Crear mi cuenta <ArrowRight size={17} /></>}</button></form></section></div></div></div>
}
